language: php

php:
  - 7.3

install:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v